import type { RankFood } from "./taste-types";

/**
 * Slim catalog for client-side ranking. No recipe bodies (those live in recipes.ts).
 */
export const RANK_FOODS: RankFood[] = [
{
    id: "crispy-hot-honey-chicken-sandwich",
    name: "Crispy hot honey chicken sandwich",
    description: "Fried chicken, hot honey glaze, soft bun, pickles.",
    flavorTags: ["savory", "spicy"],
    textureTags: ["crunchy", "juicy"],
    heaviness: "filling",
    temperature: "hot",
    adventurousness: 3,
    dietaryTags: ["contains-gluten"],
    image: "/food/crispy-hot-honey-chicken-sandwich.jpg",
    imageAlt: "Crispy fried chicken sandwich with honey drizzle",
    imageCredit: "Chad Montano / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}. Hot honey does the rest.",
    recipeMinutes: 40,
    hasRecipe: true
  },
{
    id: "spicy-vodka-rigatoni",
    name: "Spicy vodka rigatoni",
    description: "Tube pasta in creamy vodka sauce with chili heat.",
    flavorTags: ["savory", "spicy"],
    textureTags: ["creamy", "soft"],
    heaviness: "filling",
    temperature: "hot",
    adventurousness: 2,
    dietaryTags: ["vegetarian", "contains-gluten", "contains-dairy"],
    image: "/food/spicy-vodka-rigatoni.jpg",
    imageAlt: "Bowl of rigatoni in pink vodka sauce",
    imageCredit: "Chad Montano / Unsplash",
    reasonTemplate:
      "{flavor} with a {texture} sauce, and it eats {heaviness}.",
    recipeMinutes: 30,
    hasRecipe: true
  },
{
    id: "birria-tacos",
    name: "Birria tacos",
    description: "Crisped corn tortillas, shredded beef, consommé dip.",
    flavorTags: ["savory", "spicy"],
    textureTags: ["crunchy", "juicy"],
    heaviness: "filling",
    temperature: "hot",
    adventurousness: 4,
    dietaryTags: ["contains-beef", "gluten-free"],
    image: "/food/birria-tacos.jpg",
    imageAlt: "Crispy birria tacos with consommé on the side",
    imageCredit: "Emilio Sanchez / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, dipped and {heaviness}. A little more adventurous than a standard taco.",
    recipeMinutes: 180,
    hasRecipe: true
  },
{
    id: "poke-bowl",
    name: "Poke bowl",
    description: "Marinated raw fish, rice, avocado, sesame, crunchy toppings.",
    flavorTags: ["fresh", "savory"],
    textureTags: ["juicy", "soft"],
    heaviness: "medium",
    temperature: "cold",
    adventurousness: 3,
    dietaryTags: ["gluten-free", "contains-fish"],
    image: "/food/poke-bowl.jpg",
    imageAlt: "Poke bowl with tuna, avocado, and rice",
    imageCredit: "Louis Hansel / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}. Clean and cold.",
    recipeMinutes: 35,
    hasRecipe: true
  },
{
    id: "grilled-cheese-tomato-soup",
    name: "Grilled cheese and tomato soup",
    description: "Crisp buttered bread, melted cheese, hot tomato soup.",
    flavorTags: ["savory"],
    textureTags: ["crunchy", "creamy"],
    heaviness: "medium",
    temperature: "hot",
    adventurousness: 1,
    dietaryTags: ["vegetarian", "contains-gluten", "contains-dairy"],
    image: "/food/grilled-cheese-tomato-soup.jpg",
    imageAlt: "Grilled cheese sandwich next to a bowl of tomato soup",
    imageCredit: "Calum Lewis / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}. Safe favorite energy.",
    recipeMinutes: 25,
    hasRecipe: true
  },
{
    id: "sour-gummy-candy",
    name: "Sour gummy candy",
    description: "Chewy, tart candy with a sugar crust.",
    flavorTags: ["sweet", "fresh"],
    textureTags: ["soft", "crunchy"],
    heaviness: "light",
    temperature: "room",
    adventurousness: 2,
    dietaryTags: ["vegetarian", "gluten-free"],
    snack: true,
    image: "/food/sour-gummy-candy.jpg",
    imageAlt: "Pile of colorful sour gummy candies",
    imageCredit: "Sharon McCutcheon / Unsplash",
    reasonTemplate:
      "{flavor} with a {texture} chew, and it eats {heaviness}.",
    recipeMinutes: 90,
    hasRecipe: true
  },
{
    id: "mango-with-tajin",
    name: "Mango with Tajín",
    description: "Ripe mango spears dusted with chili-lime salt.",
    flavorTags: ["sweet", "spicy", "fresh"],
    textureTags: ["juicy", "soft"],
    heaviness: "light",
    temperature: "cold",
    adventurousness: 3,
    dietaryTags: ["vegan", "gluten-free"],
    snack: true,
    image: "/food/mango-with-tajin.jpg",
    imageAlt: "Fresh mango slices with chili powder",
    imageCredit: "Charles Deluvio / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}. Sweet heat, no commitment.",
    recipeMinutes: 10,
    hasRecipe: true
  },
{
    id: "garlic-butter-noodles",
    name: "Garlic butter noodles",
    description: "Simple noodles tossed in garlic butter and parsley.",
    flavorTags: ["savory"],
    textureTags: ["soft", "creamy"],
    heaviness: "medium",
    temperature: "hot",
    adventurousness: 1,
    dietaryTags: ["vegetarian", "contains-gluten", "contains-dairy"],
    image: "/food/garlic-butter-noodles.jpg",
    imageAlt: "Bowl of noodles coated in garlic butter",
    imageCredit: "Dan Gold / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}. Comfort without drama.",
    recipeMinutes: 20,
    hasRecipe: true
  },
{
    id: "miso-ramen",
    name: "Miso ramen",
    description: "Rich miso broth, springy noodles, soft egg, scallions.",
    flavorTags: ["savory"],
    textureTags: ["soft", "juicy"],
    heaviness: "filling",
    temperature: "hot",
    adventurousness: 3,
    dietaryTags: ["contains-gluten", "contains-egg"],
    image: "/food/miso-ramen.jpg",
    imageAlt: "Bowl of miso ramen with egg and scallions",
    imageCredit: "Mae Mu / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}. Broth does the heavy lifting.",
    recipeMinutes: 35,
    hasRecipe: true
  },
{
    id: "avocado-toast",
    name: "Avocado toast with chili flakes",
    description: "Smashed avocado on toasted sourdough, chili, lemon.",
    flavorTags: ["fresh", "savory"],
    textureTags: ["creamy", "crunchy"],
    heaviness: "light",
    temperature: "room",
    adventurousness: 1,
    dietaryTags: ["vegetarian", "contains-gluten", "vegan"],
    snack: true,
    image: "/food/avocado-toast.jpg",
    imageAlt: "Avocado toast with chili flakes on a plate",
    imageCredit: "Joseph Gonzalez / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}.",
    recipeMinutes: 10,
    hasRecipe: true
  },
{
    id: "korean-fried-chicken",
    name: "Korean fried chicken wings",
    description: "Twice-fried wings in sticky gochujang glaze.",
    flavorTags: ["spicy", "savory", "sweet"],
    textureTags: ["crunchy", "juicy"],
    heaviness: "filling",
    temperature: "hot",
    adventurousness: 4,
    dietaryTags: ["contains-gluten"],
    image: "/food/korean-fried-chicken.jpg",
    imageAlt: "Glazed Korean fried chicken wings",
    imageCredit: "Eiliv Aceron / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}. Sticky heat.",
    recipeMinutes: 50,
    hasRecipe: true
  },
{
    id: "caprese-salad",
    name: "Caprese salad",
    description: "Tomato, mozzarella, basil, olive oil, salt.",
    flavorTags: ["fresh", "savory"],
    textureTags: ["juicy", "soft"],
    heaviness: "light",
    temperature: "room",
    adventurousness: 1,
    dietaryTags: ["vegetarian", "gluten-free", "contains-dairy"],
    snack: true,
    image: "/food/caprese-salad.jpg",
    imageAlt: "Caprese salad with tomato, mozzarella, and basil",
    imageCredit: "Jennifer Pallian / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}.",
    recipeMinutes: 10,
    hasRecipe: true
  },
{
    id: "chocolate-lava-cake",
    name: "Chocolate lava cake",
    description: "Warm cake with a molten chocolate center.",
    flavorTags: ["sweet"],
    textureTags: ["soft", "creamy"],
    heaviness: "medium",
    temperature: "hot",
    adventurousness: 2,
    dietaryTags: ["vegetarian", "contains-gluten", "contains-dairy", "contains-egg"],
    snack: true,
    image: "/food/chocolate-lava-cake.jpg",
    imageAlt: "Chocolate lava cake with molten center",
    imageCredit: "Alex Lvrs / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}.",
    recipeMinutes: 30,
    hasRecipe: true
  },
{
    id: "ceviche",
    name: "Citrus shrimp ceviche",
    description: "Raw shrimp cured in lime with onion, cilantro, chili.",
    flavorTags: ["fresh", "spicy"],
    textureTags: ["juicy", "soft"],
    heaviness: "light",
    temperature: "cold",
    adventurousness: 5,
    dietaryTags: ["gluten-free", "contains-shellfish"],
    image: "/food/ceviche.jpg",
    imageAlt: "Bowl of citrus shrimp ceviche",
    imageCredit: "Farhad Ibrahimzade / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}. Bright and a little wild.",
    recipeMinutes: 45,
    hasRecipe: true
  },
{
    id: "mac-and-cheese",
    name: "Baked mac and cheese",
    description: "Elbow pasta under a browned cheese crust.",
    flavorTags: ["savory"],
    textureTags: ["creamy", "crunchy"],
    heaviness: "filling",
    temperature: "hot",
    adventurousness: 1,
    dietaryTags: ["vegetarian", "contains-gluten", "contains-dairy"],
    image: "/food/mac-and-cheese.jpg",
    imageAlt: "Baked mac and cheese with a golden top",
    imageCredit: "Nathan Dumlao / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}. The safe call.",
    recipeMinutes: 45,
    hasRecipe: true
  },
{
    id: "falafel-wrap",
    name: "Falafel wrap with tahini",
    description: "Crispy chickpea fritters, herbs, tahini in flatbread.",
    flavorTags: ["savory", "fresh"],
    textureTags: ["crunchy", "creamy"],
    heaviness: "medium",
    temperature: "hot",
    adventurousness: 3,
    dietaryTags: ["vegan", "contains-gluten"],
    image: "/food/falafel-wrap.jpg",
    imageAlt: "Falafel wrap cut open showing tahini and herbs",
    imageCredit: "Alan Hardman / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}.",
    recipeMinutes: 40,
    hasRecipe: true
  },
{
    id: "thai-green-curry",
    name: "Thai green curry with chicken",
    description: "Coconut green curry, chicken, basil, jasmine rice.",
    flavorTags: ["spicy", "savory", "fresh"],
    textureTags: ["creamy", "soft"],
    heaviness: "medium",
    temperature: "hot",
    adventurousness: 4,
    dietaryTags: ["gluten-free", "contains-dairy"],
    image: "/food/thai-green-curry.jpg",
    imageAlt: "Bowl of Thai green curry with rice",
    imageCredit: "Marissa Grootes / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}. Coconut heat.",
    recipeMinutes: 35,
    hasRecipe: true
  },
{
    id: "soft-serve-cone",
    name: "Vanilla soft serve cone",
    description: "Cold swirl of vanilla soft serve in a crisp cone.",
    flavorTags: ["sweet"],
    textureTags: ["creamy", "crunchy"],
    heaviness: "light",
    temperature: "cold",
    adventurousness: 1,
    dietaryTags: ["vegetarian", "contains-dairy", "contains-gluten"],
    snack: true,
    image: "/food/soft-serve-cone.jpg",
    imageAlt: "Vanilla soft serve ice cream cone",
    imageCredit: "Ian Dooley / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}.",
    recipeMinutes: 15,
    hasRecipe: true
  },
{
    id: "shakshuka",
    name: "Shakshuka",
    description: "Eggs poached in spiced tomato sauce with bread.",
    flavorTags: ["savory", "spicy"],
    textureTags: ["soft", "juicy"],
    heaviness: "medium",
    temperature: "hot",
    adventurousness: 3,
    dietaryTags: ["vegetarian", "contains-egg", "contains-gluten"],
    image: "/food/shakshuka.jpg",
    imageAlt: "Shakshuka with eggs in tomato sauce",
    imageCredit: "Toa Heftiba / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}.",
    recipeMinutes: 30,
    hasRecipe: true
  },
{
    id: "crispy-pork-belly-bao",
    name: "Crispy pork belly bao",
    description: "Steamed bun, crackly pork belly, pickled veg, hoisin.",
    flavorTags: ["savory", "sweet"],
    textureTags: ["crunchy", "soft"],
    heaviness: "medium",
    temperature: "hot",
    adventurousness: 4,
    dietaryTags: ["contains-pork", "contains-gluten"],
    image: "/food/crispy-pork-belly-bao.jpg",
    imageAlt: "Steamed bao bun filled with crispy pork belly",
    imageCredit: "Charles Deluvio / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}.",
    recipeMinutes: 90,
    hasRecipe: true
  },
{
    id: "watermelon-feta-salad",
    name: "Watermelon feta salad",
    description: "Cold watermelon, feta, mint, olive oil.",
    flavorTags: ["fresh", "sweet", "savory"],
    textureTags: ["juicy", "soft"],
    heaviness: "light",
    temperature: "cold",
    adventurousness: 2,
    dietaryTags: ["vegetarian", "gluten-free", "contains-dairy"],
    snack: true,
    image: "/food/watermelon-feta-salad.jpg",
    imageAlt: "Watermelon salad with feta and mint",
    imageCredit: "Louis Hansel / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}.",
    recipeMinutes: 15,
    hasRecipe: true
  },
{
    id: "loaded-nachos",
    name: "Loaded nachos",
    description: "Tortilla chips, melted cheese, salsa, jalapeños, crema.",
    flavorTags: ["savory", "spicy"],
    textureTags: ["crunchy", "creamy"],
    heaviness: "filling",
    temperature: "hot",
    adventurousness: 2,
    dietaryTags: ["vegetarian", "contains-dairy", "gluten-free"],
    snack: true,
    image: "/food/loaded-nachos.jpg",
    imageAlt: "Plate of loaded nachos with cheese and jalapeños",
    imageCredit: "Amirali Mirhashemian / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}.",
    recipeMinutes: 20,
    hasRecipe: true
  },
{
    id: "matcha-latte",
    name: "Iced matcha latte",
    description: "Whipped matcha over cold milk, lightly sweet.",
    flavorTags: ["fresh", "sweet"],
    textureTags: ["creamy", "soft"],
    heaviness: "light",
    temperature: "cold",
    adventurousness: 3,
    dietaryTags: ["vegetarian", "contains-dairy"],
    snack: true,
    image: "/food/matcha-latte.jpg",
    imageAlt: "Iced matcha latte in a clear glass",
    imageCredit: "Ash Edmonds / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}. A sip, not a meal.",
    recipeMinutes: 5,
    hasRecipe: true
  },
{
    id: "beef-pho",
    name: "Beef pho",
    description: "Clear aromatic broth, rice noodles, rare beef, herbs.",
    flavorTags: ["savory", "fresh"],
    textureTags: ["soft", "juicy"],
    heaviness: "medium",
    temperature: "hot",
    adventurousness: 3,
    dietaryTags: ["gluten-free", "contains-beef"],
    image: "/food/beef-pho.jpg",
    imageAlt: "Bowl of beef pho with herbs",
    imageCredit: "Anh Nguyen / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}.",
    recipeMinutes: 50,
    hasRecipe: true
  },
{
    id: "churro-bites",
    name: "Cinnamon sugar churro bites",
    description: "Fried dough sticks rolled in cinnamon sugar.",
    flavorTags: ["sweet"],
    textureTags: ["crunchy", "soft"],
    heaviness: "medium",
    temperature: "hot",
    adventurousness: 2,
    dietaryTags: ["vegetarian", "contains-gluten"],
    snack: true,
    image: "/food/churro-bites.jpg",
    imageAlt: "Cinnamon sugar churros on a plate",
    imageCredit: "Fernando Andrade / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}.",
    recipeMinutes: 35,
    hasRecipe: true
  },
{
    id: "sashimi-plate",
    name: "Salmon sashimi plate",
    description: "Thick slices of raw salmon with wasabi and soy.",
    flavorTags: ["fresh", "savory"],
    textureTags: ["soft", "juicy"],
    heaviness: "light",
    temperature: "cold",
    adventurousness: 4,
    dietaryTags: ["gluten-free", "contains-fish"],
    image: "/food/sashimi-plate.jpg",
    imageAlt: "Plate of salmon sashimi slices",
    imageCredit: "Zyanya Citrón / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}. Clean and precise.",
    recipeMinutes: 15,
    hasRecipe: true
  },
{
    id: "mushroom-risotto",
    name: "Wild mushroom risotto",
    description: "Creamy arborio rice with seared mushrooms and parmesan.",
    flavorTags: ["savory"],
    textureTags: ["creamy", "soft"],
    heaviness: "filling",
    temperature: "hot",
    adventurousness: 2,
    dietaryTags: ["vegetarian", "contains-dairy", "gluten-free"],
    image: "/food/mushroom-risotto.jpg",
    imageAlt: "Bowl of creamy mushroom risotto",
    imageCredit: "Chad Montano / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}.",
    recipeMinutes: 40,
    hasRecipe: true
  },
{
    id: "elote",
    name: "Elote (Mexican street corn)",
    description: "Grilled corn, mayo, cotija, chili, lime.",
    flavorTags: ["savory", "spicy", "sweet"],
    textureTags: ["juicy", "creamy"],
    heaviness: "medium",
    temperature: "hot",
    adventurousness: 3,
    dietaryTags: ["vegetarian", "gluten-free", "contains-dairy"],
    snack: true,
    image: "/food/elote.jpg",
    imageAlt: "Grilled Mexican street corn with cheese and chili",
    imageCredit: "Alex Lvrs / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}.",
    recipeMinutes: 20,
    hasRecipe: true
  },
{
    id: "pad-thai",
    name: "Pad Thai with shrimp",
    description: "Stir-fried rice noodles, tamarind, shrimp, peanuts, lime.",
    flavorTags: ["savory", "sweet", "spicy"],
    textureTags: ["soft", "crunchy"],
    heaviness: "medium",
    temperature: "hot",
    adventurousness: 3,
    dietaryTags: ["gluten-free", "contains-shellfish", "contains-egg"],
    image: "/food/pad-thai.jpg",
    imageAlt: "Plate of pad Thai with shrimp and peanuts",
    imageCredit: "Marissa Grootes / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}.",
    recipeMinutes: 30,
    hasRecipe: true
  },
{
    id: "affogato",
    name: "Affogato",
    description: "Vanilla gelato drowned in a shot of hot espresso.",
    flavorTags: ["sweet", "savory"],
    textureTags: ["creamy", "soft"],
    heaviness: "light",
    temperature: "cold",
    adventurousness: 2,
    dietaryTags: ["vegetarian", "contains-dairy", "gluten-free"],
    snack: true,
    image: "/food/affogato.jpg",
    imageAlt: "Affogato with espresso poured over gelato",
    imageCredit: "Nathan Dumlao / Unsplash",
    reasonTemplate:
      "{flavor} and {texture}, and it eats {heaviness}. Hot on cold.",
    recipeMinutes: 5,
    hasRecipe: true
  }
];

export function getRankFoodById(id: string): RankFood | undefined {
  return RANK_FOODS.find((food) => food.id === id);
}

export function allRankFoodIds(): string[] {
  return RANK_FOODS.map((f) => f.id);
}
